### ISSUE TITLE
Fix GlobalExecutorConfig::with_max_threads docs, mention BLOCKING_MAX_THREADS

### ISSUE THREAD

**Issue by mleonhard** [async-rs/async-global-executor#4]
The documentation of [`GlobalExecutorConfig::with_max_threads`](https://docs.rs/async-global-executor/latest/async_global_executor/struct.GlobalExecutorConfig.html#method.with_max_threads) says:

> ```rust
> pub fn with_max_threads(mut self: Self, max_threads: usize) -> Self
> ```
> Use the specified value as the maximum number of threads.

This is false.  Async-global-executor uses the `max_threads` value only to decide how many threads to use for running async tasks.  Calls to [`async_global_executor::spawn_blocking.html`](https://docs.rs/async-global-executor/latest/async_global_executor/fn.spawn_blocking.html) bypass this limit.  The correct way to configure the maximum threads used by async-global-executor is to set the `BLOCKING_MAX_THREADS` environment variable, as explained in the [`blocking` crate docs](https://docs.rs/blocking/latest/blocking/).

Related: https://github.com/smol-rs/blocking/issues/24

**Comment by Keruspe** [comment]
Indeed, thanks for the report.

The documentation should now be more explicit about this in 2.0.3
